### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by danya201272** [probe4aiur/HS8#1]
If the shotgun to reload the shotgun loses the ability to shoot 6 rounds and becomes a normal mp7

**Comment by probe4aiur** [comment]
Are you absolutely sure it's related to the reload? There's a known bug caused by grenades/flash bangs in which the item's previous slot acts like a shotgun. E.g: a person has a grenade, shotgun, and USP. Once the nade is thrown, the USP acts like the shotgun. Trying to fix but Smod doesn't have support for it at the moment.

**Comment by danya201272** [comment]
I dont sure
